# Generated by Django 5.0.2 on 2024-03-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_image_alter_post_title'),
        ('post', '0002_post_user_alter_post_image_alter_post_title'),
    ]

    operations = [
    ]
