# Generated by Django 5.0.2 on 2024-03-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_merge_20240301_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
