# Generated by Django 5.0.2 on 2024-03-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
