# Generated by Django 5.0.2 on 2024-02-29 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='user',
        ),
    ]
