# Generated by Django 5.0.2 on 2024-02-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_remove_art_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='tags',
            field=models.CharField(help_text='Tags (Separated by space. Example: #nature #waterfall)', max_length=200),
        ),
    ]
