# Generated by Django 5.0.2 on 2024-02-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_alter_art_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
