# Generated by Django 5.0.2 on 2024-02-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_alter_art_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Art',
            new_name='Post',
        ),
    ]
